# Exercício 1

## n2das

In [1]:
import numpy as np

#* OBS: Valores conforme figura 2.3 e tabela de exemplo numérico do pdf

#Iniciação e definição do numero de nós e canos
nv=5
nc=7

#Iniciação e definição de matriz de conecções e a de condutâncias
conec=np.zeros(shape=(nc,2),dtype=int)
conduc=np.zeros(shape=(nc,nc))
conduc[0][0],conduc[1][1],conduc[2][2],conduc[3][3],conduc[4][4],conduc[5][5],conduc[6][6]=2,2,1,2,1,2,2
conec=[[1,2],[2,3],[3,4],[4,5],[5,2],[5,3],[5,1]]

## Método 1

In [2]:
def fazer_matriz_A_1(conec,nc,nv,conduc):
    #Inicia a matriz A que será retornada
    A=np.zeros(shape=(nv,nv))

    for i in range(nc): # percorre as linhas da matriz de conecções
        for j in range(nv): # percorre as linhas da matriz A
            for k in range(nv):
                if(j+1==conec[i][0]): #se a linha corresponder ap nó de n1da 
                    if(k+1==conec[i][1]): # e se a coluna corresponder ao nó de n2da
                        
                        # adição de elementos conforme a matriz ClocK
                        A[j][j]=A[j][j]+conduc[i][i]
                        A[j][k]=A[j][k]-conduc[i][i]
                        A[k][j]=A[k][j]-conduc[i][i]
                        A[k][k]=A[k][k]+conduc[i][i]
    
    return A

print(fazer_matriz_A_1(conec,nc,nv,conduc))

[[ 4. -2.  0.  0. -2.]
 [-2.  5. -2.  0. -1.]
 [ 0. -2.  5. -1. -2.]
 [ 0.  0. -1.  3. -2.]
 [-2. -1. -2. -2.  7.]]


## Método 2

In [3]:
def fazer_matriz_A_2(conec,nc,nv,conduc):
    #Inicia a matriz A que será retornada
    A=np.zeros(shape=(nv,nv))
    
    n1,n2=0,0

    for i in range(nc): # percorre as linhas da matriz de conecções
        
        #recebimento dos nós da linha i da matriz de conecções
        n1,n2=conec[i][0],conec[i][1]

        # adição de elementos conforme a matriz ClocK
        A[n1-1][n1-1]=A[n1-1][n1-1]+conduc[i][i]    
        A[n1-1][n2-1]=A[n1-1][n2-1]-conduc[i][i]
        A[n2-1][n1-1]=A[n2-1][n1-1]-conduc[i][i]
        A[n2-1][n2-1]=A[n2-1][n2-1]+conduc[i][i]
                        
    
    return A

print(fazer_matriz_A_2(conec,nc,nv,conduc))

[[ 4. -2.  0.  0. -2.]
 [-2.  5. -2.  0. -1.]
 [ 0. -2.  5. -1. -2.]
 [ 0.  0. -1.  3. -2.]
 [-2. -1. -2. -2.  7.]]
