# Exercício 3 e 4

## Entradas


In [1]:
import numpy as np

#* OBS: Valores conforme figura 2.3 e tabela de exemplo numérico do pdf

#Iniciação e definição do numero de nós e canos
nv=5
nc=7
nB=1
QB=3
natm=3

#Iniciação e definição de matriz de conecções e a de condutâncias
conec=np.zeros(shape=(nc,2),dtype=int)
conduc=np.zeros(shape=(nc,nc))
conduc[0][0],conduc[1][1],conduc[2][2],conduc[3][3],conduc[4][4],conduc[5][5],conduc[6][6]=2,2,1,2,1,2,2
conec=[[1,2],[2,3],[3,4],[4,5],[5,2],[5,3],[5,1]]

## Monta matriz A

In [2]:
def retorna_matriz_A(conec,nc,nv,conduc):
    #Inicia a matriz A que será retornada
    A=np.zeros(shape=(nv,nv),dtype=np.float64)
    
    n1,n2=0,0

    for i in range(nc): # percorre as linhas da matriz de conecções
        
        #recebimento dos nós da linha i da matriz de conecções
        n1,n2=conec[i][0],conec[i][1]

        # adição de elementos conforme a matriz ClocK
        A[n1-1][n1-1]=A[n1-1][n1-1]+conduc[i][i]    
        A[n1-1][n2-1]=A[n1-1][n2-1]-conduc[i][i]
        A[n2-1][n1-1]=A[n2-1][n1-1]-conduc[i][i]
        A[n2-1][n2-1]=A[n2-1][n2-1]+conduc[i][i]
                        
    
    return A

## Função de formação da matriz à e direita

In [3]:

def retorna_matriz_Ã(A,natm):
    rng=len(A[0])
    Ã=A
    for i in range(0,rng):
        if(i==natm-1):
            Ã[natm-1][i]=1
        else:
            Ã[natm-1][i]=0
    return Ã

def retorna_matriz_direita(A,nB,QB):
    rng=len(A[0])
    D=np.zeros(rng,dtype=np.float64)
    for i in range(0,rng):
        if(i==nB-1): D[i]=QB
        else: D[i]=0
    return D



## Resolução do sistema

In [4]:
def resolve_sistema(Ã,D):
    #Obtém a matriz Inversa da matriz Ã
    I=np.linalg.inv(Ã)

    #Obtém vetor de pressões
    P=I@D
    return P

def vetor_vazoes_nodos(A,P):
    Q=A@P
    return Q

A=retorna_matriz_A(conec,nc,nv,conduc)

Ã=retorna_matriz_Ã(A,natm)

Dn=retorna_matriz_direita(A,nB,QB)

P=resolve_sistema(Ã,Dn)

Qn=vetor_vazoes_nodos(A,P)

## Obtenção da matriz D 

In [5]:
def retorna_matriz_D(nc,nv,conec):
    l=nc
    c=nv
    D=np.zeros(shape=(l,c),dtype=np.float64)
    for i in range(l):
        n1,n2=conec[i][0],conec[i][1]
        D[i][n1-1]=1
        D[i][n2-1]=-1
    return D
Dc=retorna_matriz_D(nc,nv,conec)
print(Dc)

[[ 1. -1.  0.  0.  0.]
 [ 0.  1. -1.  0.  0.]
 [ 0.  0.  1. -1.  0.]
 [ 0.  0.  0.  1. -1.]
 [ 0. -1.  0.  0.  1.]
 [ 0.  0. -1.  0.  1.]
 [-1.  0.  0.  0.  1.]]


## Obtenção do vetor de vazões nos canos

In [6]:
def retorna_vazoes_canos(conduc,D,P):
    Qc=conduc@D@P
    W=(Qc.transpose())@(D@P)
    return Qc,W
Qc,W=retorna_vazoes_canos(conduc,Dc,P)
print('\nQc=',Qc)
print('\nW=',W)


Qc= [ 1.43181818  1.36363636 -0.40909091 -0.40909091 -0.06818182  1.22727273
 -1.56818182]

W= 4.193181818181818


## 